# Default values for prometheus-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: luxas/k8s-prometheus-adapter
  tag: v0.2.0-beta.0
  pullPolicy: Always
service:
  name: custom-metrics-apiserver
  type: ClusterIP
  externalPort: 443
  internalPort: 6443
  tls:
    enable: true
    ca: |-
      -----BEGIN CERTIFICATE-----
      MIIC7TCCAdWgAwIBAgIJAJ5jkSJF0IaUMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNV
      BAMMAmNhMB4XDTE4MDExNTEwNDAxNFoXDTE5MDExNTEwNDAxNFowDTELMAkGA1UE
      AwwCY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzVgwHw7HKeACl
      aE38pwNxd460vtaSn+Fr35xYWAjxfUdz+RuuQxvYM8Fu4iOk24fCfFR183l461nr
      Jo2qWOJjVeHEAY3HPwanjXr/RjLlnwoYFnoRsf6vSDhuMObSFAgbUDiSHi75cwTc
      zwh/Zkl3+t4LagGExvH/LuhWXFDhmODwWiFwYjDEVu5fy3bNs6k5hEf+VcjBd6AE
      uQ81Q5efawx3baG+4ah3xC29o9ybTailsry72LDeYQh8EMCJfKMYkMW+PlKsDDu5
      L4dqXrUVkV+xhZTtz9QwxaFEsnnvZ8QfGNp2RwdmT9JHcBgy+NTyeG3aUjcu1izP
      +gD95yiVAgMBAAGjUDBOMB0GA1UdDgQWBBThtvFq3ZTaBwQy13XGlgHGx2XKUTAf
      BgNVHSMEGDAWgBThtvFq3ZTaBwQy13XGlgHGx2XKUTAMBgNVHRMEBTADAQH/MA0G
      CSqGSIb3DQEBCwUAA4IBAQCkT54JyDH/Y2+I16n7cCSDl3NTwWvVS8fzr4Tfn5Xp
      pA+L1KMt0GtkO9/Ewr8AxC6dbva67pxakQp0FlGuauRPIHs3QETIHr2n8aQ00TQk
      H28vegQ7dPc8GpMFshZcBZvLD3hPZDQskEsb5Hdl9DC0pvXJH+ywQg3M58orhYoB
      S+d5wQzhBDjqGLsmTKkBWxpN/cKXdnz4i7FpupRX/uogqptY8zpvoG1sdg9X4osN
      AfmMRG410Gk3PSIeiPCEZO5KtClRhgfCi7257z062yTT3K0r8L10z6D7DWJqhDD3
      LO6zzfp1u7Dx5hMBbZlFMppLbfEas5WJk+ahtzl+12nY
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAnAy031u6dTJI9vLZoP0irRxEjr0VJ1nkYHFjkvzTdJA3H+2B
      LSGUhWyDRdtlL1I7xnUdV51kWgRw+325A1WdW6e98UqTiL64r+CAwSH1CTVW34+J
      X5wyEVkwI++H9PKrIXycXzeadopmP6GebTyD5ljc0VvctD7mIVjTJnYM9V0ll565
      DfHini1A0xHLqjA22XVf7jHNcrCnFR9PRnX2OvbCGljmr4YaR32OKEKB4UK5zeQg
      +b1JY4LE6yxIHptTYe3XUBki9f2qgcknVRSZKyXyfzlwoM+P3Hs/XnQgEhoceh7n
      OiKg0cTokH8jOzigckIDSkJKLu5e3gYd8Zl+PwIDAQABAoIBACVYVSDvDtxlQFj5
      HWQNsHLFRRLz5VAZjzIVcMMIhoJq0QZvDG8EjkqwAWqCauC8SVnhRThmjlGMpo1J
      NTG7F4GLz0Ujl9Mt8X0FuUp/GekuPrAZ5cJf2wuT0JWJCXxxZssIy1NuNyUPUhEA
      WK3Dwb0qnw3rchIgy2pHm6Ckt80wMdgDARzL7ofqA/l1gr9rFEpEutiy7JfEi3hC
      c//oXPMu1kbWeo4hF1EFTYffapwYWgcmuFRN8MUs3xoF/fmCzcmgYoS8Ab9wQBtT
      cfzqaAUeYos8W7zy+OI5inqIstjxHuz410T7vZvlhZwimMFd6wkCbumlGgGvEAn0
      +jw7dCECgYEAxsTVQN1rL+yyRsWVwiA+rrK+75cdvkTKT/MzCnisZTWgrWmeeWhJ
      /7Uyy4A0eczz9KC2JCHJ4cQKS2u0MDYDkID2biALj7NvZer9l4b7qC/s9ftgJr0x
      JnZH+cvi5VMINsjl2Ie7wVnSm5lxX3FDGB3r1BkDz6Qu6WSfpizIqJMCgYEAyPsO
      hwN1mmh6U2CS4px0tAD1bMqL6OAvza9fskF5cTt29n/QaBxHs6QKaJpk03bH+mVA
      RvaI1bck1ZL5CkVr9qVzyPL3VhfCLjOgtdzpZTRPxyWnbJoPAZHGKV3C9R77DE86
      KdPYoVGiwORgqvrAgswebaxQgRc7ve3Ld68L+yUCgYArqXkesoSlFl1i5mwrJGIg
      hesjPhKuhPXb8hQ4LKHR6aHN9fF1wc7feLIbuaHNT5QXHGZmMXXjPej1AEeof3Tw
      /SMkta1Ud5n0zVW/P0twenaW4g0Q9WYiiMDuwjapIUAgqKi0k7xOkKiOvXoF+R8/
      4PK4uHX52prjcdMP8a5yOQKBgDB4A1fiKLF1MtL6vlGyQ57JgGadLkKaFk03Vw/J
      JH1/RsBJsLv63fvfurbhTSGGStIDKw4yFGveAB8Vk8O7XD8eRZ8XoTh9AFJeFwrk
      3NCQXhD77rWNLcNGIZEGUKcGsqqUTMWblmnJI0P7j6iMUnL4wPnYDY4kST8TovcZ
      Gv2VAoGBAMN1MBhUHFJYVE6hkBRkrTjkm1MDNX9QGN+cb7YdPQdiLk6P5+A5tEC4
      /n+VOBqAcJvEAJ/5fdn7H7w7qgZTsE1ipXlyFyjbfmgLyVCSaDMyltuvKLCdj6nv
      Oh9uMFri0+DDuMxzD2Ij41OyxtZQ6G7AoNRddbPyQfvEsU24Jkdo
      -----END RSA PRIVATE KEY-----
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDgTCCAmmgAwIBAgIUGEUNQw/gu+k0yrrMcnSYvC2NypYwDQYJKoZIhvcNAQEL
      BQAwDTELMAkGA1UEAwwCY2EwHhcNMTgwMTE1MTAzODAwWhcNMjMwMTE0MTAzODAw
      WjAjMSEwHwYDVQQDExhjdXN0b20tbWV0cmljcy1hcGlzZXJ2ZXIwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcDLTfW7p1Mkj28tmg/SKtHESOvRUnWeRg
      cWOS/NN0kDcf7YEtIZSFbINF22UvUjvGdR1XnWRaBHD7fbkDVZ1bp73xSpOIvriv
      4IDBIfUJNVbfj4lfnDIRWTAj74f08qshfJxfN5p2imY/oZ5tPIPmWNzRW9y0PuYh
      WNMmdgz1XSWXnrkN8eKeLUDTEcuqMDbZdV/uMc1ysKcVH09GdfY69sIaWOavhhpH
      fY4oQoHhQrnN5CD5vUljgsTrLEgem1Nh7ddQGSL1/aqBySdVFJkrJfJ/OXCgz4/c
      ez9edCASGhx6Huc6IqDRxOiQfyM7OKByQgNKQkou7l7eBh3xmX4/AgMBAAGjgcIw
      gb8wDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFAilA2EN
      Yt7sypj5VV4LC+G7PObdMB8GA1UdIwQYMBaAFOG28WrdlNoHBDLXdcaWAcbHZcpR
      MF8GA1UdEQRYMFaCJ2N1c3RvbS1tZXRyaWNzLWFwaXNlcnZlci5jdXN0b20tbWV0
      cmljc4IrY3VzdG9tLW1ldHJpY3MtYXBpc2VydmVyLmN1c3RvbS1tZXRyaWNzLnN2
      YzANBgkqhkiG9w0BAQsFAAOCAQEAqG4jod494hywDIcJiXyO2oMtIEv13iX4ytga
      qxcwm9N6Ln2meOJDyiek2xm80lR/eBOWmEZfh2UuFKRAiw6gfjnZxnuFEJsSg5Dj
      Izx1fqSjZ1Qrhoj1hXyajeuMnhnoxb4+EO54wOhqeS6Cqtw6xOKmK40yKBV4Y196
      Nr57VD03Z94nImlPq3TZm1eMSsQo0onmaq71zjzbZR1Nu4qLc4pTDBSpUHezIMcq
      SExI9tYttggRXDo0dbqFGKoNBurfcVL6KkyiLr0q8mkALRvVXodhjdyR1nJVI5Zb
      lVgLfXzcEDPtzRGCydRQst48qtf6ZFOKG6sjM0XUBeTf4+geAw==
      -----END CERTIFICATE-----
  # Current version of the custom-metrics API for K8s 
  version: v1beta1
  authentication: 
    method: kubeconfig
    kubeconfig: |-
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lKQUoxenlQcEhTb3FETUEwR0NTcUdTSWIzRFFFQkN3VUFNQll4RkRBU0JnTlYKQkFNTUN6RXdMak13TGpBdU1UUXpNQjRYRFRFNE1ERXhOekUyTkRJek1Wb1hEVEk0TURFeE5URTJOREl6TVZvdwpGakVVTUJJR0ExVUVBd3dMTVRBdU16QXVNQzR4TkRNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDZEsrdDJMRmpOenkyZUJ1UDZueFEzam5SNkZXMGROV0EyZmFQZmpJT0RobVlhcHk0MkRDVXAKME8xdUpIVTVvMW9ubFplelVQc0ZYNUlIMmlXSW13cVBWL2E4YjFXSkt1by9uTTRhSy92M2ovbXIrSnNWd1NRZgp2dnp0L3ovUmc1WUVGZjlscGZqNzlmYVdzNVgvdWNXbGJaQi9mQlNlWEl2dmZRdytneXY0MGV0a3pvN3FnMnBPCmN3YzdaQWVFS2hpQlVkMlF3blptb3RFSGNqMFMweXYzSFQwRy9saTUvaHJNWDlJMGJnazhVZGplVmI3d1hTcy8KazVSRDcvK1phM0diOHF5alRVcGczcXdpUXN0NFVHVThycFhPRjByV0hBMmVqS1VaTTlOaHU1NHN4RFRPajlCMgo4TmJERTRmN083cC82SlJXSnNFVDFEWkZuWE1LUTJGbEFnTUJBQUdqZ1lVd2dZSXdIUVlEVlIwT0JCWUVGTC90CkJDVFo3QkRsbGtWOHQxZWlYK0xBakxFRk1FWUdBMVVkSXdRL01EMkFGTC90QkNUWjdCRGxsa1Y4dDFlaVgrTEEKakxFRm9ScWtHREFXTVJRd0VnWURWUVFEREFzeE1DNHpNQzR3TGpFME00SUpBSjF6eVBwSFNvcURNQXdHQTFVZApFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBM2s4M3JhUnJrCjE0cE9RS3hvZ05pKzVDN2lnazRMTEloUXlha205Y1BFODMwTkZoTHpXc0YxQmcrSWhFUWZQZDdmMEt2VDZEQXYKMDhSWE5TL3hGSVJTQmxpSzAxL3plNE44a1hXbmI1M3NMYys3b1JUMU5PNVNuSjlqRjJWSW8yMFo2b0ZEdXhidgpWOEFiRUJieXM1QTB3ekI5QVF2OElURVQ1YWJaV1l5R3htR0hTYjYrblJNQXU4WTJ0R3Z0UEdwZVpZaVY5Mk9yCmVRL0xQclBtOWhCZE9zN2JkTDJuLzUvV0FicmpxQnZZR2tvL3dJTkl3eVNLM2FRS2t3MDRJREFNRlByUU5veWYKdEJ6RXNZTDdsV3RQcG1wUzZUWVVQd0xsYi94UG9Gd1BuQUNvUmlUcTZubmlCM0ZzUXB1eHNPejBmTS9yU0M5RApJdDVvZkprTkZDZ1AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
          server: https://10.30.0.104:443
        name: juju-cluster
      contexts:
      - context:
          cluster: juju-cluster
          user: cma-custom-metrics-apiserver
        name: juju-context
      current-context: juju-context
      kind: Config
      preferences: {}
      users:
      - name: cma-custom-metrics-apiserver
        user:
          # username: system:serviceaccount:custom-metrics:cma-custom-metrics-apiserver
          token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjdXN0b20tbWV0cmljcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjbWEtY3VzdG9tLW1ldHJpY3MtYXBpc2VydmVyLXRva2VuLTZzdGdnIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImNtYS1jdXN0b20tbWV0cmljcy1hcGlzZXJ2ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyMjMyZTI0Ni0wMDE0LTExZTgtODA1NS0wMGEwYTU5YjA1ZTkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y3VzdG9tLW1ldHJpY3M6Y21hLWN1c3RvbS1tZXRyaWNzLWFwaXNlcnZlciJ9.HfTFRHDadGmdcc2T3xJdDRBQYXGgEJ1G7l5tErJHkD2ORlFEhZLbskZrVNx-VmhGfdHO1zdHRw3ZzIMEzxEhSowSSa9KsRcv8Pno8sngSONFcR5DXfdIdtF1uNnt2R5n_Tvx4WOlwLVmtigdIUz7yKef1ZFs620LflgwooxKXzictu0RWtLERD9NsYBn76NLCms_AJmd6Ryem-A675VjyGoaru1sxCHIt1tuoGLu3-cOUyr2Mx8GamTMb4cuDRM0UrbBzMaf9Z5EbMKS1zBtYAoaepLYLV8QL8AofMZkAOICcXsIUAW75KFZ_mfNvyT1T7LOCsGS8SU5IWNrmtcIhw

rbac: 
  install: true
  apiVersion: v1beta1

resources: 
  limits:
   cpu: 500m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi

prometheus: 
  service: 
    url: http://10.30.0.140
    port: 30999


