apiVersion: v1
kind: ServiceAccount
metadata:
  name: miner-metrics
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: miner-metrics
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: miner-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: miner-metrics
subjects:
- kind: ServiceAccount
  name: miner-metrics
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        image: samnco/mwc-miner-metrics:latest
        imagePullPolicy: Always
        env:
        - name: WALLET_ID
          value: "etnk1J5msRQJmLJDBcLPuRcHbTtuz8BpWJvS5mD9RooqBzsN2vvxwxA26AeaDVRyegg1fmNY8VuDtSEHt3kcpT5S3eB6WJCWei"
        - name: LOAD_INCLUSTER_CONFIG
          value: "true"
        - name: GRAFANA_GRAPH_ID
          value: kubernetes-custom-resources
        - name: GRAFANA_SERVICE_HOST
          value: "10.30.0.140"
        - name: GRAFANA_SERVICE_PORT
          value: "30902"         
#        - name: EXCLUDE_POD_NAMESPACES
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
        ports:
        - containerPort: 5050
          name: web
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
      dnsPolicy: ClusterFirst
      serviceAccountName: miner-metrics
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: cluster-metrics
  # namespace: etn2
  labels:
    app: metrics
spec:
  type: NodePort
  selector:
    app: metrics
  ports:
  - name: web
    nodePort: 30505
    port: 80
    targetPort: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-metrics
  labels:
    service-monitor: sample-metrics-app
    demo: autoscaling
    app: metrics
spec:
  selector:
    matchLabels:
      app: metrics
#  namespaceSelector:
#    matchNames:
#    - etn2
  endpoints:
  - port: web
