apiVersion: v1
kind: Service
metadata:
  name: tf-serving-8cpu
  namespace: default
spec:
  ports:
  - name: grpc
    port: 9000
    targetPort: 9000
  selector:
    app: tf-serving-8cpu
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-serving-8cpu
  labels: 
    app: tf-serving-8cpu
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tf-serving-8cpu
    spec:
      containers:
      - image: samnco/tf-serving:cpu
        name: tf-serving
        command: ["/entrypoint.sh"]
        imagePullPolicy: IfNotPresent
        env: 
        - name: PORT
          value: "9000"
        - name: MODEL_NAME
          value: "inception"
        - name: MODEL_PATH
          value: "/model-data"
        ports:
        - containerPort: 9000
        readinessProbe:
          tcpSocket:
            port: 9000
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        resources: 
          requests: 
            cpu: 8000m
            memory: 8192Mi
          limits: 
            cpu: 8000m
            memory: 8192Mi            
        volumeMounts:
        - mountPath: /model-data
          name: tf-serving-data
      restartPolicy: Always
      volumes:
      - name: tf-serving-data
        hostPath: 
          path: /model-data
          type: Directory
